apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cli-tool
  template:
    metadata:
      labels:
        app: cli-tool
    spec:
      containers:
      - name: cli-tool
        image: localhost:5000/cli-tool:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: local-docker-registry-secret
