apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-images
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-images
  template:
    metadata:
      labels:
        app: db-images
    spec:
      containers:
      - name: db-images
        image: localhost:5000/db-images:latest
        ports:
        - containerPort: 5432
      imagePullSecrets:
      - name: local-docker-registry-secret
